name: Build Firmware
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
        git describe --dirty --tags
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        pip install platformio
    - name: Build firmware
      run: |
        platformio run --environment teensy32
        platformio run --environment teensy40
        cp .pio/build/teensy32/firmware.hex firmware_teensy32.hex
        cp .pio/build/teensy40/firmware.hex firmware_teensy40.hex
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        path: |
          firmware_teensy32.hex
          firmware_teensy40.hexl
    - name: Upload firmware to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.hex
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
      if: startsWith(github.ref, 'refs/tags/')
